# Generated by Django 4.0.2 on 2022-02-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('comment', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=12)),
            ],
        ),
    ]
