# Generated by Django 4.0.1 on 2022-02-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_likes_remove_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Цена'),
        ),
    ]
